api:
  id: "19990334"
  listener:
    path: "/*"
http:
  listener:
    host: "0.0.0.0"
    port: "8081"
    
salesforce: 
  username: ${secure::security.salesforce.username}
  password: ${secure::security.salesforce.password}
  token: ${secure::security.salesforce.token}
  responseTimeout: "60"
  connectionTimeout: "60"
  async-data-retry:
    frequency: "5000"
    attempts: "3"